const lvlId = {
    "0": "Banned",
    "1": "Guest",
    "2": "Validating",
    "3": "Member",
    "4": "Contributor",
    "5": "Group Leader",
    "6": "Power Uploader",
    "9": "VIP",
    "10": "Public Relations",
    "11": "Forum Moderator",
    "12": "Moderator (Global)",
    "15": "Developer",
    "16": "Administrator 1",
    "20": "Administrator 2"
};
const lang = {
    SA: "Arabic",
    BD: "Bengali",
    BG: "Bulgarian",
    MM: "Burmese",
    CT: "Catalan",
    CN: "Chinese (Simp)",
    HK: "Chinese (Trad)",
    CZ: "Czech",
    DK: "Danish",
    NL: "Dutch",
    GB: "English",
    PH: "Filipino",
    FI: "Finnish",
    FR: "French",
    DE: "German",
    GR: "Greek",
    HU: "Hungarian",
    ID: "Indonesian",
    IT: "Italian",
    JP: "Japanese",
    KR: "Korean",
    LT: "Lithuanian",
    MY: "Malay",
    MN: "Mongolian",
    IR: "Persian",
    PL: "Polish",
    BR: "Portuguese (Br)",
    PT: "Portuguese (Pt)",
    RO: "Romanian",
    RU: "Russian",
    RS: "Serbo-Croatian",
    ES: "Spanish (Es)",
    MX: "Spanish (LATAM)",
    SE: "Swedish",
    TH: "Thai",
    TR: "Turkish",
    UA: "Ukrainian",
    VN: "Vietnamese"
};
const pub = {
    1: "Ongoing",
    2: "Completed",
    3: "Cancelled",
    4: "Hiatus"
};

exports.ids = {lvlId, lang, pub};